name: Hello actions
description: Greet Someone
author: myself

inputs:
  MY_NAME:
    description: who to greet
    required: true
    default: world

runs:
  using: docker
  image: Dockerfile

branding:
  icon: mic
  color: purple